# Generated by Django 5.2 on 2025-05-07 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='funcaoexercida',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funcoes'),
        ),
        migrations.AlterField(
            model_name='tripulante',
            name='funcao_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcao_principal', to='main.funcoes'),
        ),
        migrations.AlterField(
            model_name='tripulante',
            name='funcao_secundaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcao_secundaria', to='main.funcoes'),
        ),
    ]
