# Generated by Django 5.2 on 2025-06-06 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_funcoes_alter_funcaoexercida_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripulante',
            name='horas_nave',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripulante',
            name='nome_de_guerra',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripulante',
            name='pontuacao_atual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripulante',
            name='funcao_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcao_secundaria', to='main.funcoes'),
        ),
    ]
